site_name: Reemote
site_description: An API for controlling remote systems.
site_url: https://https://reemote.org/

repo_name: kimjarvis/reemote
repo_url: https://https://github.com/kimjarvis/reemote

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Installation: installation.md
  - Inventory: inventory.md
  - Deployment: deployment.md
  - API Documentation: redoc-static.html
